import type { Article, ExpressionConcept, LearningUnit } from '../domain/models'

export const expandedArticles: Article[] = [
  {
    id: 'article-handscroll-time',
    slug: 'a-painting-that-unrolls-like-time',
    title: 'A Painting That Unrolls Like Time',
    eyebrow: 'Chinese art · Ways of seeing',
    summary: 'How the physical form of a Chinese handscroll turns viewing into a journey through space, sequence, and attention.',
    topicTags: ['Art & Design', 'Culture & Stories'],
    difficulty: 'Gentle',
    estimatedMinutes: 6,
    source: 'Original learning article informed by The Metropolitan Museum of Art',
    sourceUrl: 'https://www.metmuseum.org/essays/chinese-handscrolls',
    license: 'Original content · Source facts attributed for personal learning',
    contentVersion: 1,
    accent: 'moss',
    origin: 'built_in',
    featuredExpressionIds: ['unit-reveal', 'unit-frame'],
    blocks: [
      {
        id: 'scroll-1',
        type: 'paragraph',
        text: 'A Chinese handscroll is a long painting on paper or silk. When it is not being viewed, it remains rolled up. Its full image exists, but it is not presented to the eye all at once.',
      },
      {
        id: 'scroll-2',
        type: 'paragraph',
        text: 'The viewer usually unrolls the scroll from right to left, pausing over a section about as wide as the shoulders. Each turn of the hands reveals a new stretch of landscape while the earlier section is gently rolled away.',
      },
      {
        id: 'scroll-3',
        type: 'paragraph',
        text: 'This physical rhythm changes the act of looking. A mountain may arrive after a quiet river; a group of travellers may disappear before a village comes into view. The painting controls neither the viewer nor the speed completely, but it offers a sequence.',
      },
      {
        id: 'scroll-4',
        type: 'paragraph',
        text: 'Unlike a picture fixed on a wall, the handscroll has a frame that is always moving. What can be seen depends on where the hands stop. The viewer does not stand outside a finished scene but helps decide how the scene unfolds through time.',
      },
      {
        id: 'scroll-5',
        type: 'paragraph',
        text: 'A digital screen can show the whole scroll in a second, yet speed changes the experience. The older format reminds us that seeing is not only receiving an image. It can also be a patient action shaped by touch, memory, and expectation.',
      },
    ],
  },
  {
    id: 'article-bamboo-renews',
    slug: 'the-quiet-speed-of-bamboo',
    title: 'The Quiet Speed of Bamboo',
    eyebrow: 'Plants · Material culture',
    summary: 'A short look at bamboo as a fast-growing grass, a renewable material, and a plant whose usefulness comes from many possible forms.',
    topicTags: ['Nature & Animals', 'Culture & Stories', 'Science & Society'],
    difficulty: 'Gentle',
    estimatedMinutes: 6,
    source: 'Original learning article informed by Royal Botanic Gardens, Kew',
    sourceUrl: 'https://www.kew.org/plants/giant-bamboo',
    license: 'Original content · Source facts attributed for personal learning',
    contentVersion: 1,
    accent: 'clay',
    origin: 'built_in',
    featuredExpressionIds: ['unit-regenerate', 'unit-versatile'],
    blocks: [
      {
        id: 'bamboo-1',
        type: 'paragraph',
        text: 'Bamboo is often called a tree because it can rise far above a person, but it belongs to the grass family. Some giant species form hollow, jointed stems and can reach more than twenty metres in height.',
      },
      {
        id: 'bamboo-2',
        type: 'paragraph',
        text: 'Its growth can be remarkably fast. Kew notes that mature giant bamboo may grow as much as thirty centimetres a day during its peak season. That speed helps the plant compete for light in a crowded forest.',
      },
      {
        id: 'bamboo-3',
        type: 'paragraph',
        text: 'The plant can also regenerate from its roots after harvesting. New stems rise from a living underground system, so useful material can return without planting an entirely new forest each time.',
      },
      {
        id: 'bamboo-4',
        type: 'paragraph',
        text: 'This makes bamboo a versatile material. Across different places, people have shaped it into scaffolding, furniture, baskets, chopsticks, musical instruments, charcoal, and many other objects. The same stem can enter very different forms of life.',
      },
      {
        id: 'bamboo-5',
        type: 'paragraph',
        text: 'Fast growth alone does not make every use sustainable. Species, habitat, harvest methods, transport, and product life all matter. Bamboo is most interesting when it is understood not as a miracle solution, but as a plant with unusual possibilities and real limits.',
      },
    ],
  },
  {
    id: 'article-insects-light',
    slug: 'when-night-insects-lose-the-sky',
    title: 'When Night Insects Lose the Sky',
    eyebrow: 'Animal behaviour · Light',
    summary: 'What three-dimensional flight research suggests about insects circling lamps—and why the behaviour may be confusion rather than attraction.',
    topicTags: ['Nature & Animals', 'Science & Society', 'CET-4 themes'],
    difficulty: 'Stretch',
    estimatedMinutes: 7,
    source: 'Original learning article based on Fabian et al., Nature Communications (2024)',
    sourceUrl: 'https://www.nature.com/articles/s41467-024-44785-3',
    license: 'Original content · Based on an open-access research article',
    contentVersion: 1,
    accent: 'ink',
    origin: 'built_in',
    featuredExpressionIds: ['unit-orient', 'unit-disrupt'],
    blocks: [
      {
        id: 'moth-1',
        type: 'paragraph',
        text: 'People have long described moths as creatures attracted to flame. Yet high-speed cameras and three-dimensional flight tracking suggest a different story. Many flying insects do not steer directly toward a lamp.',
      },
      {
        id: 'moth-2',
        type: 'paragraph',
        text: 'In natural darkness, flying insects can use the brightest broad area above them to orient their bodies. Keeping their backs toward the sky helps them remain upright while the ground stays below.',
      },
      {
        id: 'moth-3',
        type: 'paragraph',
        text: 'A nearby artificial lamp disrupts that relationship. The brightest area is no longer the distant sky overhead. As an insect turns its back toward the lamp, its body may tilt, circle, stall, or even become inverted.',
      },
      {
        id: 'moth-4',
        type: 'paragraph',
        text: 'The resulting path can look like attraction from a human distance. Up close, however, it is more like a control system receiving a misleading signal. A useful response in one environment becomes dangerous in another.',
      },
      {
        id: 'moth-5',
        type: 'paragraph',
        text: 'This explanation does not answer every question about every insect or every kind of light. It does change the problem we see. The insects may not be choosing the lamp; they may be losing the stable sky that once told them which way was up.',
      },
    ],
  },
  {
    id: 'article-painting-care',
    slug: 'the-patient-work-behind-an-old-painting',
    title: 'The Patient Work Behind an Old Painting',
    eyebrow: 'Art conservation · Material evidence',
    summary: 'Why caring for an old painting begins with close observation, collaboration, and respect for every physical layer.',
    topicTags: ['Art & Design', 'Culture & Stories', 'Science & Society'],
    difficulty: 'Gentle',
    estimatedMinutes: 7,
    source: 'Original learning article informed by the Getty Museum Paintings Conservation Department',
    sourceUrl: 'https://www.getty.edu/museum/paintings-conservation/',
    license: 'Original content · Source facts attributed for personal learning',
    contentVersion: 1,
    accent: 'clay',
    origin: 'built_in',
    featuredExpressionIds: ['unit-preserve', 'unit-layer'],
    blocks: [
      {
        id: 'care-1',
        type: 'paragraph',
        text: 'An old painting arrives in a conservation studio with more than an image. It carries wood or canvas, ground material, paint, varnish, repairs, cracks, dust, and the effects of changing light and temperature.',
      },
      {
        id: 'care-2',
        type: 'paragraph',
        text: 'Conservation begins with an effort to preserve what has survived, not to make the work look newly painted. Conservators observe closely, record its condition, and ask what has changed before deciding whether to act.',
      },
      {
        id: 'care-3',
        type: 'paragraph',
        text: 'A painting is built from layers. Some belong to the artist, while others may come from later varnish or repair. Scientific imaging and material analysis can help specialists understand which layer they are seeing and how it reacts.',
      },
      {
        id: 'care-4',
        type: 'paragraph',
        text: 'The work is collaborative. Conservators may speak with art historians, scientists, curators, photographers, and the institution that owns the painting. A treatment can reveal information, but every change also carries responsibility.',
      },
      {
        id: 'care-5',
        type: 'paragraph',
        text: 'Patience is therefore a technical skill as well as a personal quality. Sometimes the best decision is a careful repair; sometimes it is improved storage or a slower plan. Caring for the future begins by reading the evidence already present.',
      },
    ],
  },
  {
    id: 'article-forest-orbit',
    slug: 'how-a-forest-becomes-a-pattern-from-orbit',
    title: 'How a Forest Becomes a Pattern from Orbit',
    eyebrow: 'Earth science · Remote sensing',
    summary: 'How satellite instruments turn reflected energy and laser returns into repeated evidence about vegetation, fire, and forest structure.',
    topicTags: ['Science & Society', 'Nature & Animals', 'CET-4 themes'],
    difficulty: 'Stretch',
    estimatedMinutes: 7,
    source: 'Original learning article informed by NASA Earthdata',
    sourceUrl: 'https://www.earthdata.nasa.gov/centers/lp-daac',
    license: 'Original content · Source facts attributed for personal learning',
    contentVersion: 1,
    accent: 'moss',
    origin: 'built_in',
    featuredExpressionIds: ['unit-detect', 'unit-monitor'],
    blocks: [
      {
        id: 'orbit-1',
        type: 'paragraph',
        text: 'From orbit, a forest is not seen in the same way that a person sees it from a path. Satellite instruments receive reflected energy, heat, or laser returns and turn those signals into measurements arranged across a map.',
      },
      {
        id: 'orbit-2',
        type: 'paragraph',
        text: 'Different sensors can detect different features. Some measurements help show vegetation greenness or surface temperature. Others can provide evidence about canopy height, vertical structure, wildfire, water stress, or changes in land cover.',
      },
      {
        id: 'orbit-3',
        type: 'paragraph',
        text: 'A single image is useful, but repeated observation allows researchers to monitor change over time. When measurements are aligned to the same grid, patterns from different days or years can be compared more carefully.',
      },
      {
        id: 'orbit-4',
        type: 'paragraph',
        text: 'The resulting map is not the forest itself. Clouds, resolution, sensor limits, seasons, and analysis choices shape what becomes visible. Ground observations remain important for checking what the signals mean in a real place.',
      },
      {
        id: 'orbit-5',
        type: 'paragraph',
        text: 'Remote sensing is powerful because it connects distance with repetition. It lets people notice broad changes that no single observer could watch continuously, while still requiring careful interpretation of the evidence.',
      },
    ],
  },
]

export const expandedConcepts: ExpressionConcept[] = [
  {
    id: 'concept-reveal',
    canonicalForm: 'reveal',
    expressionType: 'word',
    coreConceptEn: 'to remove what kept something from being seen or known, allowing what was already there to come into view',
    coreConceptZh: '移开遮挡或未知状态，让原本已经存在的东西进入视野或认知。',
    mentalModel: 'present but hidden → barrier opens → visible or known',
    boundaries: ['Reveal does not necessarily mean create; the thing may have existed before it became visible.'],
    contentVersion: 1,
  },
  {
    id: 'concept-frame',
    canonicalForm: 'frame',
    expressionType: 'word',
    coreConceptEn: 'a boundary or structure that selects what is included and shapes how it is understood',
    coreConceptZh: '通过边界或结构选择哪些内容进入视野，并影响我们如何理解它。',
    mentalModel: 'wide reality → selected boundary → shaped view',
    boundaries: ['A frame can be physical, visual, linguistic, or mental.'],
    contentVersion: 1,
  },
  {
    id: 'concept-regenerate',
    canonicalForm: 'regenerate',
    expressionType: 'word',
    coreConceptEn: 'to form or grow again after part of a living or working system has been lost',
    coreConceptZh: '系统的一部分失去后，凭借仍存在的生命或结构再次生长、形成。',
    mentalModel: 'loss or removal → surviving source → renewed growth',
    boundaries: ['Regeneration is renewed formation, not simply keeping the original part unchanged.'],
    contentVersion: 1,
  },
  {
    id: 'concept-versatile',
    canonicalForm: 'versatile',
    expressionType: 'word',
    coreConceptEn: 'able to move successfully across several different uses, roles, or situations',
    coreConceptZh: '同一种能力、材料或事物可以有效进入多种用途、角色或情境。',
    mentalModel: 'one resource → adapts across paths → many effective uses',
    boundaries: ['Versatile suggests useful range, not that something is perfect for every purpose.'],
    contentVersion: 1,
  },
  {
    id: 'concept-orient',
    canonicalForm: 'orient',
    expressionType: 'word',
    coreConceptEn: 'to establish position or direction by relating yourself or something else to a reference',
    coreConceptZh: '借助一个参照物确定自己或某物的位置、方向与朝向。',
    mentalModel: 'uncertain position + reference → direction becomes stable',
    boundaries: ['The reference may be physical, spatial, social, or conceptual.'],
    contentVersion: 1,
  },
  {
    id: 'concept-disrupt',
    canonicalForm: 'disrupt',
    expressionType: 'word',
    coreConceptEn: 'to break into an ongoing pattern so that it can no longer continue in its usual way',
    coreConceptZh: '闯入一个正在运行的模式，使它无法继续按原来的方式进行。',
    mentalModel: 'stable process → interference enters → normal flow breaks',
    boundaries: ['Disruption changes continuity; it does not always destroy the whole system.'],
    contentVersion: 1,
  },
  {
    id: 'concept-preserve',
    canonicalForm: 'preserve',
    expressionType: 'word',
    coreConceptEn: 'to carry something valuable through time by protecting it from loss or damaging change',
    coreConceptZh: '保护有价值的东西，使它穿过时间而不被丢失或遭受破坏性改变。',
    mentalModel: 'valued state + pressure of time → protection → continued presence',
    boundaries: ['Preserving is not always freezing something exactly as it is; careful change may support survival.'],
    contentVersion: 1,
  },
  {
    id: 'concept-layer',
    canonicalForm: 'layer',
    expressionType: 'word',
    coreConceptEn: 'one level of material, information, or meaning placed over, under, or among other levels',
    coreConceptZh: '材料、信息或意义中的一个层次，与其他层次上下叠放或共同构成整体。',
    mentalModel: 'separate levels → overlap or stack → one structured whole',
    boundaries: ['A layer is only one level of a larger structure, not the whole structure itself.'],
    contentVersion: 1,
  },
  {
    id: 'concept-detect',
    canonicalForm: 'detect',
    expressionType: 'word',
    coreConceptEn: 'to notice that something is present by receiving a signal or piece of evidence',
    coreConceptZh: '通过信号或证据察觉某物的存在，即使它并未直接显现在眼前。',
    mentalModel: 'hidden presence → signal arrives → presence becomes known',
    boundaries: ['Detection shows presence or change; it may not explain the cause.'],
    contentVersion: 1,
  },
  {
    id: 'concept-monitor',
    canonicalForm: 'monitor',
    expressionType: 'word',
    coreConceptEn: 'to observe something repeatedly so that change, condition, or risk can be followed over time',
    coreConceptZh: '持续或反复观察，使变化、状态或风险能够沿时间被追踪。',
    mentalModel: 'repeated observations → comparison through time → change becomes trackable',
    boundaries: ['Monitoring is ongoing observation, not a single look or automatic control.'],
    contentVersion: 1,
  },
]

export const expandedLearningUnits: LearningUnit[] = [
  {
    id: 'unit-reveal', articleId: 'article-handscroll-time', blockId: 'scroll-2', expressionConceptId: 'concept-reveal', selectedText: 'reveals',
    sentenceText: 'Each turn of the hands reveals a new stretch of landscape while the earlier section is gently rolled away.',
    contextClues: ['The landscape already exists on the rolled paper.', 'What changes when the hands turn the scroll?'],
    grammarAndCollocations: ['verb · each turn reveals something', 'reveal + object / reveal that…'],
    simpleEnglishMeaning: 'allows a hidden part of the painting to be seen',
    contextualMeaningEn: 'Turning the scroll removes the rolled covering from the next section, bringing that landscape into view.',
    contextualSupportZh: '手卷转动时，原本卷藏的下一段山水进入视野。',
    coreConnection: 'The painted landscape was already present; the movement removes what kept it unseen.',
    relatedContexts: [
      { sentence: 'The scan revealed a crack beneath the surface.', meaningEn: 'The scan made a hidden crack known.', supportZh: '扫描让表面下的裂缝显现出来。', connection: 'Evidence removes the crack from an unknown state.' },
      { sentence: 'Her final question revealed what she truly valued.', meaningEn: 'The question made an inner priority noticeable.', supportZh: '最后的问题显露了她真正看重的东西。', connection: 'A private attitude becomes externally knowable.' },
    ],
    transfer: { prompt: 'Which situation best fits the same core movement?', context: 'The clouds opened and revealed the mountain peak.', choices: [{ id: 'a', label: 'The peak already existed but became visible.' }, { id: 'b', label: 'The clouds built a new mountain.' }, { id: 'c', label: 'The peak moved underground.' }], correctChoiceId: 'a', feedback: 'The mountain was present before the clouds stopped hiding it.' },
    contentVersion: 1,
  },
  {
    id: 'unit-frame', articleId: 'article-handscroll-time', blockId: 'scroll-4', expressionConceptId: 'concept-frame', selectedText: 'frame',
    sentenceText: 'Unlike a picture fixed on a wall, the handscroll has a frame that is always moving.',
    contextClues: ['Only one section of the long scroll can be seen at a time.', 'The hands decide where the visible section begins and ends.'],
    grammarAndCollocations: ['countable noun · a frame', 'inside a frame / frame a view / frame a question'],
    simpleEnglishMeaning: 'the boundary that decides what part is visible',
    contextualMeaningEn: 'The visible edges of the handscroll shift as the viewer rolls and unrolls it.',
    contextualSupportZh: '这里的 frame 是决定当前可见范围的边界，它会随手卷移动。',
    coreConnection: 'A changing boundary repeatedly selects one part of the larger painting for attention.',
    relatedContexts: [
      { sentence: 'The doorway framed a narrow view of the sea.', meaningEn: 'Its edges selected and shaped the visible view.', supportZh: '门框圈定了一小片海景。', connection: 'A physical boundary chooses what enters sight.' },
      { sentence: 'The report frames the issue as a design problem.', meaningEn: 'It chooses a structure for understanding the issue.', supportZh: '报告把这个问题放进设计问题的理解框架。', connection: 'A mental boundary shapes interpretation rather than sight.' },
    ],
    transfer: { prompt: 'What does “frame” mainly do here?', context: 'The photographer used the branches to frame the bird.', choices: [{ id: 'a', label: 'They create a visual boundary around the bird.' }, { id: 'b', label: 'They teach the bird to fly.' }, { id: 'c', label: 'They remove the bird from the scene.' }], correctChoiceId: 'a', feedback: 'The branches select and shape the part of the scene receiving attention.' },
    contentVersion: 1,
  },
  {
    id: 'unit-regenerate', articleId: 'article-bamboo-renews', blockId: 'bamboo-3', expressionConceptId: 'concept-regenerate', selectedText: 'regenerate',
    sentenceText: 'The plant can also regenerate from its roots after harvesting.',
    contextClues: ['The visible stems have been harvested.', 'A living underground root system remains.'],
    grammarAndCollocations: ['verb · the plant regenerates', 'regenerate from + surviving source / regenerate tissue'],
    simpleEnglishMeaning: 'grow again from the part that remains alive',
    contextualMeaningEn: 'After stems are removed, the surviving root system can produce new growth.',
    contextualSupportZh: '地上竹秆被采收后，仍存活的地下根系可以再次长出新竹。',
    coreConnection: 'Loss is followed by renewed growth from a source that survived.',
    relatedContexts: [
      { sentence: 'Some animals can regenerate damaged tissue.', meaningEn: 'They can form living tissue again after damage.', supportZh: '一些动物能在损伤后重新形成组织。', connection: 'A living system rebuilds a lost part.' },
      { sentence: 'The neighbourhood regenerated after years of decline.', meaningEn: 'Activity and life returned after a period of loss.', supportZh: '社区在多年衰退后重新恢复活力。', connection: 'The renewal is social rather than biological.' },
    ],
    transfer: { prompt: 'Which example shows regeneration?', context: 'Choose the closest core movement.', choices: [{ id: 'a', label: 'New grass grows from roots left after a fire.' }, { id: 'b', label: 'A stone stays unchanged in a box.' }, { id: 'c', label: 'A chair is moved across a room.' }], correctChoiceId: 'a', feedback: 'A surviving living source produces growth after loss.' },
    contentVersion: 1,
  },
  {
    id: 'unit-versatile', articleId: 'article-bamboo-renews', blockId: 'bamboo-4', expressionConceptId: 'concept-versatile', selectedText: 'versatile',
    sentenceText: 'This makes bamboo a versatile material.',
    contextClues: ['The next sentence lists many very different objects.', 'The material can be shaped for building, household use, music, and fuel.'],
    grammarAndCollocations: ['adjective · a versatile material', 'highly versatile / versatile enough to…'],
    simpleEnglishMeaning: 'useful in many different ways',
    contextualMeaningEn: 'Bamboo can be adapted successfully for many kinds of products and purposes.',
    contextualSupportZh: '竹子能够被有效加工成许多用途不同的物品。',
    coreConnection: 'One material moves across several practical paths without losing its usefulness.',
    relatedContexts: [
      { sentence: 'A pencil is a versatile drawing tool.', meaningEn: 'It can produce many kinds of marks and effects.', supportZh: '铅笔能产生多种线条与效果，是用途灵活的绘画工具。', connection: 'One tool works across several visual tasks.' },
      { sentence: 'She is a versatile performer who can sing, act, and dance.', meaningEn: 'Her ability remains effective across several roles.', supportZh: '她能唱、能演、能跳，适应多种表演角色。', connection: 'The flexible range belongs to a person rather than a material.' },
    ],
    transfer: { prompt: 'Why is the bag described as versatile?', context: 'The same bag works for class, short trips, and outdoor sketching.', choices: [{ id: 'a', label: 'It serves several different situations well.' }, { id: 'b', label: 'It can only be used once.' }, { id: 'c', label: 'It is the most expensive bag.' }], correctChoiceId: 'a', feedback: 'Versatility is useful range across different roles or situations.' },
    contentVersion: 1,
  },
  {
    id: 'unit-orient', articleId: 'article-insects-light', blockId: 'moth-2', expressionConceptId: 'concept-orient', selectedText: 'orient',
    sentenceText: 'In natural darkness, flying insects can use the brightest broad area above them to orient their bodies.',
    contextClues: ['The next sentence mentions staying upright.', 'The bright sky acts as a reference point.'],
    grammarAndCollocations: ['verb · orient their bodies', 'orient yourself toward / orient something around'],
    simpleEnglishMeaning: 'work out which direction their bodies should face',
    contextualMeaningEn: 'The insects use the bright sky as a reference for keeping a stable body position.',
    contextualSupportZh: '昆虫借助明亮天空这个参照，确定身体应该朝向哪里。',
    coreConnection: 'A reference removes uncertainty about direction and position.',
    relatedContexts: [
      { sentence: 'She paused to orient herself on the unfamiliar trail.', meaningEn: 'She found her position and direction using nearby signs.', supportZh: '她停下来借助周围标志确认自己在陌生小路上的方位。', connection: 'The reference is spatial.' },
      { sentence: 'The introduction orients readers to the main debate.', meaningEn: 'It gives readers a reference structure for understanding.', supportZh: '导言帮助读者确定理解主要争论的方向。', connection: 'The reference is conceptual rather than physical.' },
    ],
    transfer: { prompt: 'What helps the sailor orient the boat?', context: 'The sailor checks the stars before changing direction.', choices: [{ id: 'a', label: 'The stars provide a directional reference.' }, { id: 'b', label: 'The stars repair the boat.' }, { id: 'c', label: 'The stars make the sea warmer.' }], correctChoiceId: 'a', feedback: 'Orientation becomes possible when a stable reference is available.' },
    contentVersion: 1,
  },
  {
    id: 'unit-disrupt', articleId: 'article-insects-light', blockId: 'moth-3', expressionConceptId: 'concept-disrupt', selectedText: 'disrupts',
    sentenceText: 'A nearby artificial lamp disrupts that relationship.',
    contextClues: ['The normal relationship is between the bright sky and the insect’s upright body.', 'After the lamp appears, flight may circle or stall.'],
    grammarAndCollocations: ['verb · the lamp disrupts the relationship', 'disrupt a process / pattern / service'],
    simpleEnglishMeaning: 'breaks the normal pattern so it stops working properly',
    contextualMeaningEn: 'The lamp interferes with the sky-based reference that normally supports stable flight.',
    contextualSupportZh: '灯光干扰了以天空为参照的正常关系，使飞行控制无法照常运行。',
    coreConnection: 'A new signal enters an ongoing control process and breaks its usual flow.',
    relatedContexts: [
      { sentence: 'Heavy rain disrupted train service.', meaningEn: 'The rain prevented the service from continuing normally.', supportZh: '暴雨打乱了列车的正常运行。', connection: 'An outside event breaks an established process.' },
      { sentence: 'The unexpected colour disrupts the calm pattern.', meaningEn: 'It interrupts the visual order.', supportZh: '意外出现的颜色打破了平静的视觉规律。', connection: 'The broken continuity is visual.' },
    ],
    transfer: { prompt: 'Which event is a disruption?', context: 'Choose the event that breaks an ongoing pattern.', choices: [{ id: 'a', label: 'A power cut stops the workshop in the middle of production.' }, { id: 'b', label: 'The workshop opens at its usual time.' }, { id: 'c', label: 'A finished object stays on a shelf.' }], correctChoiceId: 'a', feedback: 'The power cut enters a working process and prevents its normal continuation.' },
    contentVersion: 1,
  },
  {
    id: 'unit-preserve', articleId: 'article-painting-care', blockId: 'care-2', expressionConceptId: 'concept-preserve', selectedText: 'preserve',
    sentenceText: 'Conservation begins with an effort to preserve what has survived, not to make the work look newly painted.',
    contextClues: ['The painting has already lasted for many years.', 'The goal is not to replace age with a new appearance.'],
    grammarAndCollocations: ['verb · preserve what has survived', 'preserve evidence / memory / material'],
    simpleEnglishMeaning: 'protect the surviving parts so they can continue into the future',
    contextualMeaningEn: 'Conservators try to keep the authentic material and evidence from being lost or damaged further.',
    contextualSupportZh: '修复人员首先保护已经保存下来的真实材料与证据，让它们继续存在。',
    coreConnection: 'Protection helps something valuable remain present while time and damage create pressure.',
    relatedContexts: [
      { sentence: 'The archive preserves letters from the early studio.', meaningEn: 'It protects the letters so they remain available through time.', supportZh: '档案馆保存早期工作室的信件，使其不随时间消失。', connection: 'The protected value is historical evidence.' },
      { sentence: 'Freezing can preserve food for longer.', meaningEn: 'It slows damaging change so the food remains usable.', supportZh: '冷冻减缓破坏性变化，让食物保存更久。', connection: 'The protected value is a usable physical condition.' },
    ],
    transfer: { prompt: 'Which action is mainly about preservation?', context: 'Choose the closest example.', choices: [{ id: 'a', label: 'A museum controls humidity to reduce future damage.' }, { id: 'b', label: 'A painter starts a completely new canvas.' }, { id: 'c', label: 'A visitor changes the title of a work.' }], correctChoiceId: 'a', feedback: 'Controlling humidity protects existing material as it moves through time.' },
    contentVersion: 1,
  },
  {
    id: 'unit-layer', articleId: 'article-painting-care', blockId: 'care-3', expressionConceptId: 'concept-layer', selectedText: 'layers',
    sentenceText: 'A painting is built from layers.',
    contextClues: ['The paragraph names paint, varnish, and later repair.', 'Specialists need to identify which level they are observing.'],
    grammarAndCollocations: ['countable noun · layers', 'a layer of paint / layered meaning'],
    simpleEnglishMeaning: 'separate levels of material placed over or under one another',
    contextualMeaningEn: 'The painting contains several levels of material that were added at different stages.',
    contextualSupportZh: '画作由不同阶段加入、彼此叠放的多层材料构成。',
    coreConnection: 'Several distinct material levels overlap to form the object now seen as one painting.',
    relatedContexts: [
      { sentence: 'A thin layer of mist covered the river.', meaningEn: 'Mist formed a level over the river’s surface.', supportZh: '一层薄雾覆盖在河面上。', connection: 'The layer is a physical covering.' },
      { sentence: 'The story has several layers of meaning.', meaningEn: 'Different levels of interpretation exist together.', supportZh: '这个故事包含多层意义。', connection: 'The levels are conceptual rather than material.' },
    ],
    transfer: { prompt: 'Why is “layer” useful here?', context: 'The app adds a privacy layer between the user and the public network.', choices: [{ id: 'a', label: 'It adds one protective level within a larger system.' }, { id: 'b', label: 'It removes every part of the system.' }, { id: 'c', label: 'It describes the colour blue.' }], correctChoiceId: 'a', feedback: 'A layer is one level that sits within or over other levels.' },
    contentVersion: 1,
  },
  {
    id: 'unit-detect', articleId: 'article-forest-orbit', blockId: 'orbit-2', expressionConceptId: 'concept-detect', selectedText: 'detect',
    sentenceText: 'Different sensors can detect different features.',
    contextClues: ['The satellite receives reflected energy, heat, or laser returns.', 'The features are known through measurements rather than direct human sight.'],
    grammarAndCollocations: ['verb · sensors detect features', 'detect a signal / change / presence'],
    simpleEnglishMeaning: 'notice that a feature is present through the signal it gives',
    contextualMeaningEn: 'Sensors register evidence that allows particular conditions or features to be identified.',
    contextualSupportZh: '传感器接收特定信号，从而察觉某些地表特征或状态的存在。',
    coreConnection: 'A feature that is distant or not directly visible becomes known through its signal.',
    relatedContexts: [
      { sentence: 'The device detected smoke before anyone saw a flame.', meaningEn: 'A signal made the presence of smoke known early.', supportZh: '设备在人看到火焰前就探测到了烟。', connection: 'Evidence reveals a hidden risk.' },
      { sentence: 'She detected a change in his tone.', meaningEn: 'A small signal made an emotional change noticeable.', supportZh: '她从语气中察觉到变化。', connection: 'The signal is social and auditory rather than electronic.' },
    ],
    transfer: { prompt: 'What has been detected?', context: 'The camera records a small rise in night-time temperature.', choices: [{ id: 'a', label: 'A change has become noticeable through measurement.' }, { id: 'b', label: 'The camera created the temperature.' }, { id: 'c', label: 'No signal was received.' }], correctChoiceId: 'a', feedback: 'Detection makes a presence or change known through evidence.' },
    contentVersion: 1,
  },
  {
    id: 'unit-monitor', articleId: 'article-forest-orbit', blockId: 'orbit-3', expressionConceptId: 'concept-monitor', selectedText: 'monitor',
    sentenceText: 'A single image is useful, but repeated observation allows researchers to monitor change over time.',
    contextClues: ['The sentence contrasts one image with repeated observation.', 'Measurements from different dates are compared.'],
    grammarAndCollocations: ['verb · researchers monitor change', 'monitor progress / health / risk over time'],
    simpleEnglishMeaning: 'watch and measure repeatedly to follow how something changes',
    contextualMeaningEn: 'Researchers compare repeated satellite observations to track the forest’s changing condition.',
    contextualSupportZh: '研究人员通过反复比较卫星观测，持续追踪森林状态如何变化。',
    coreConnection: 'Repeated observations create a time path that a single measurement cannot provide.',
    relatedContexts: [
      { sentence: 'Doctors monitored her recovery for several weeks.', meaningEn: 'They observed her condition repeatedly as it changed.', supportZh: '医生连续数周观察她的恢复情况。', connection: 'Repeated health observations make progress trackable.' },
      { sentence: 'The team monitors comments after each design update.', meaningEn: 'They repeatedly observe feedback for change or risk.', supportZh: '团队在每次设计更新后持续查看反馈。', connection: 'The tracked condition is user response.' },
    ],
    transfer: { prompt: 'Which action is monitoring?', context: 'Choose the action that creates evidence across time.', choices: [{ id: 'a', label: 'Recording river height every morning for a year.' }, { id: 'b', label: 'Looking at the river once and leaving.' }, { id: 'c', label: 'Naming the river on a map.' }], correctChoiceId: 'a', feedback: 'Monitoring depends on repeated observation that makes change trackable.' },
    contentVersion: 1,
  },
]
