import type { Article, ExpressionConcept, LearningUnit } from '../domain/models'
import { expandedArticles, expandedConcepts, expandedLearningUnits } from './expansion'

export const articles: Article[] = [
  {
    id: 'article-ink-breathes',
    slug: 'when-ink-learns-to-breathe',
    title: 'When Ink Learns to Breathe',
    eyebrow: 'Art · Visual language',
    summary:
      'A quiet look at how ink painters use water, empty space, and restraint to make a still image feel alive.',
    topicTags: ['Art & Design', 'Culture & Stories'],
    difficulty: 'Gentle',
    estimatedMinutes: 8,
    source: 'Original article written for Dedicated to Fx',
    license: 'Original content · Personal learning use',
    contentVersion: 1,
    accent: 'moss',
    origin: 'built_in',
    featuredExpressionIds: [
      'unit-absorb',
      'unit-emerge',
      'unit-restraint',
      'unit-reflect',
      'unit-trace',
      'unit-perspective',
    ],
    blocks: [
      {
        id: 'ink-1',
        type: 'paragraph',
        text: 'An ink painting often begins before the brush touches paper. The artist slows down, studies the amount of water in the brush, and notices how quickly the paper will absorb it. This pause is not empty time. It is part of the painting.',
      },
      {
        id: 'ink-2',
        type: 'paragraph',
        text: 'When ink meets paper, control becomes a conversation. A wet brush can create a soft cloud of grey, while a drier brush leaves broken, energetic lines. Mountains may emerge from a few uneven washes. A bird may be suggested by one dark eye and the turn of a wing.',
      },
      {
        id: 'ink-3',
        type: 'paragraph',
        text: 'The power of the image often comes from restraint. Instead of describing every leaf, the painter offers just enough for the viewer to continue the scene in the mind. What is left open is not unfinished. It is an invitation.',
      },
      {
        id: 'ink-4',
        type: 'paragraph',
        text: 'White space can reflect silence, distance, mist, or light. It changes according to the marks around it. Beside a dark cliff, it may feel like air. Between two small boats, it can become a wide river.',
      },
      {
        id: 'ink-5',
        type: 'paragraph',
        text: 'Time also remains visible. A pale edge records where water once spread. A rough stroke carries the speed of the hand. Each trace allows us to sense an action that has already ended, so the still image holds a memory of movement.',
      },
      {
        id: 'ink-6',
        type: 'paragraph',
        text: 'This way of seeing changes perspective. The painting is not only an object to look at; it is a space the viewer completes. Ink, paper, hand, and imagination each do less than everything, yet together they create more than any one part could explain.',
      },
    ],
  },
  {
    id: 'article-city-fox',
    slug: 'the-fox-at-the-edge-of-the-city',
    title: 'The Fox at the Edge of the City',
    eyebrow: 'Nature · Adaptation',
    summary:
      'What an urban fox can teach us about adaptation, attention, and the invisible borders between human and wild spaces.',
    topicTags: ['Nature & Animals', 'Science & Society'],
    difficulty: 'Gentle',
    estimatedMinutes: 6,
    source: 'Original article written for Dedicated to Fx',
    license: 'Original content · Personal learning use',
    contentVersion: 1,
    accent: 'clay',
    origin: 'built_in',
    featuredExpressionIds: [],
    blocks: [
      {
        id: 'fox-1',
        type: 'paragraph',
        text: 'Just before sunrise, a red fox crosses an empty bicycle lane. It moves with confidence, but it does not belong to the city in the same way that people do. It reads the streets through smell, sound, and habit.',
      },
      {
        id: 'fox-2',
        type: 'paragraph',
        text: 'Urban foxes adapt without becoming tame. They learn when traffic grows quiet and where food is likely to appear. Their success depends on attention rather than strength.',
      },
      {
        id: 'fox-3',
        type: 'paragraph',
        text: 'The fox reveals a border that is easy to ignore. A park is designed for people during the day, yet at night it becomes a path for animals. One place can serve several lives at different hours.',
      },
      {
        id: 'fox-4',
        type: 'paragraph',
        text: 'Watching such an animal does not require turning it into a pet or a symbol. Sometimes the most respectful response is simply to notice how carefully another creature has learned to live beside us.',
      },
    ],
  },
  {
    id: 'article-leaving-things-out',
    slug: 'why-designers-leave-things-out',
    title: 'Why Designers Leave Things Out',
    eyebrow: 'Design · Attention',
    summary:
      'A short essay about why clarity often comes from choosing what not to show.',
    topicTags: ['Art & Design', 'Science & Society'],
    difficulty: 'Stretch',
    estimatedMinutes: 7,
    source: 'Original article written for Dedicated to Fx',
    license: 'Original content · Personal learning use',
    contentVersion: 1,
    accent: 'ink',
    origin: 'built_in',
    featuredExpressionIds: [],
    blocks: [
      {
        id: 'design-1',
        type: 'paragraph',
        text: 'A page can contain every available feature and still fail to help anyone. When all elements ask for attention at once, the user must spend energy deciding where to begin.',
      },
      {
        id: 'design-2',
        type: 'paragraph',
        text: 'Good design is often an act of editing. A designer identifies the most important action, reduces competing signals, and gives the remaining elements room to form a clear order.',
      },
      {
        id: 'design-3',
        type: 'paragraph',
        text: 'This simplicity is not the same as emptiness. It is deliberate. Each absence protects something else: a quiet margin protects reading, a limited palette protects hierarchy, and a short label protects momentum.',
      },
      {
        id: 'design-4',
        type: 'paragraph',
        text: 'What has been removed may never be noticed, but its effect can still be felt. The page becomes easier to enter because the designer has already made several difficult choices on the user’s behalf.',
      },
    ],
  },
  ...expandedArticles,
]

export const concepts: ExpressionConcept[] = [
  {
    id: 'concept-absorb',
    canonicalForm: 'absorb',
    expressionType: 'word',
    coreConceptEn: 'to take something in so that it becomes held inside',
    coreConceptZh: '把外来的东西吸收进内部，并在其中留住。',
    mentalModel: 'outside → taken in → held within',
    boundaries: ['The thing taken in may be liquid, information, attention, or cost.'],
    contentVersion: 1,
  },
  {
    id: 'concept-emerge',
    canonicalForm: 'emerge',
    expressionType: 'word',
    coreConceptEn: 'to move from hidden or unclear into a state where it can be seen or known',
    coreConceptZh: '从隐藏、模糊或尚未形成的状态中逐渐显现。',
    mentalModel: 'unseen → crossing a boundary → visible',
    boundaries: ['It suggests becoming noticeable, not simply being created instantly.'],
    contentVersion: 1,
  },
  {
    id: 'concept-restraint',
    canonicalForm: 'restraint',
    expressionType: 'word',
    coreConceptEn: 'the deliberate holding back of force, action, or expression',
    coreConceptZh: '主动收住力量、行动或表达，为其他可能性留下空间。',
    mentalModel: 'available force → intentionally held back',
    boundaries: ['It is controlled limitation, not inability or lack of skill.'],
    contentVersion: 1,
  },
  {
    id: 'concept-reflect',
    canonicalForm: 'reflect',
    expressionType: 'word',
    coreConceptEn: 'to return, present, or bring something back into view or thought',
    coreConceptZh: '让某种东西返回、呈现，或重新进入意识。',
    mentalModel: 'something goes out or stays within → comes back into view',
    boundaries: ['The grammar tells us whether light, a quality, or a thought is being brought back.'],
    contentVersion: 1,
  },
  {
    id: 'concept-trace',
    canonicalForm: 'trace',
    expressionType: 'word',
    coreConceptEn: 'a small remaining sign that lets us follow something no longer fully present',
    coreConceptZh: '某件事离开后留下的微小线索，使我们仍能追随它。',
    mentalModel: 'past presence → remaining mark → path back',
    boundaries: ['A trace is usually partial; it is evidence, not the whole thing.'],
    contentVersion: 1,
  },
  {
    id: 'concept-perspective',
    canonicalForm: 'perspective',
    expressionType: 'word',
    coreConceptEn: 'a position or frame that shapes how something is seen and understood',
    coreConceptZh: '观察事物时所处的位置或框架，它会改变我们看见和理解的方式。',
    mentalModel: 'where you stand → what becomes visible → how you understand',
    boundaries: ['It can be a visual viewpoint or a way of thinking.'],
    contentVersion: 1,
  },
  ...expandedConcepts,
]

export const learningUnits: LearningUnit[] = [
  {
    id: 'unit-absorb',
    articleId: 'article-ink-breathes',
    blockId: 'ink-1',
    expressionConceptId: 'concept-absorb',
    selectedText: 'absorb',
    sentenceText: 'The artist slows down, studies the amount of water in the brush, and notices how quickly the paper will absorb it.',
    contextClues: ['What is “it” in this sentence?', 'Think about what paper does when water touches its surface.'],
    grammarAndCollocations: ['verb · the paper is the subject', 'absorb + liquid / information / cost'],
    simpleEnglishMeaning: 'to take the water in and hold it inside',
    contextualMeaningEn: 'The paper takes water into its fibres instead of leaving it on the surface.',
    contextualSupportZh: '这里是说纸张把水吸进纤维内部。',
    coreConnection: 'Water moves from outside the paper to being held within it.',
    relatedContexts: [
      { sentence: 'She was too absorbed in the sketch to hear the door.', meaningEn: 'Her attention was completely taken into the activity.', supportZh: '她的注意力完全沉浸在素描中。', connection: 'What is taken in here is attention rather than liquid.' },
      { sentence: 'The small studio absorbed the extra cost.', meaningEn: 'The studio accepted and carried the cost.', supportZh: '工作室承担了额外成本。', connection: 'The cost is taken into the studio’s own burden.' },
    ],
    transfer: {
      prompt: 'Which reading keeps the same core movement?',
      context: 'The dark cloth absorbed most of the afternoon light.',
      choices: [
        { id: 'a', label: 'The cloth took the light in, so little came back.' },
        { id: 'b', label: 'The cloth created new light from its surface.' },
        { id: 'c', label: 'The cloth moved away from the light.' },
      ],
      correctChoiceId: 'a',
      feedback: 'Here, light is the thing taken in and held rather than returned.',
    },
    contentVersion: 1,
  },
  {
    id: 'unit-emerge',
    articleId: 'article-ink-breathes',
    blockId: 'ink-2',
    expressionConceptId: 'concept-emerge',
    selectedText: 'emerge',
    sentenceText: 'Mountains may emerge from a few uneven washes.',
    contextClues: ['The mountains are not drawn with complete outlines.', 'What becomes visible when the washes begin to suggest a shape?'],
    grammarAndCollocations: ['intransitive verb · no direct object', 'emerge from + source or hidden state'],
    simpleEnglishMeaning: 'to become visible or clear from something less clear',
    contextualMeaningEn: 'The suggestion of mountains gradually becomes visible through the washes.',
    contextualSupportZh: '几层不均匀的墨色逐渐显出山的形态。',
    coreConnection: 'The mountains move from being unseen in the marks to being recognisable.',
    relatedContexts: [
      { sentence: 'A pattern emerged after the interviews were compared.', meaningEn: 'A shared pattern became clear.', supportZh: '比较访谈后，一个共同模式逐渐显现。', connection: 'What crosses into visibility is an idea, not a physical object.' },
      { sentence: 'The moth emerged from its case at night.', meaningEn: 'The moth came out from a place that had hidden it.', supportZh: '飞蛾夜里从蛹壳中出来。', connection: 'Here the hidden-to-visible movement is physical.' },
    ],
    transfer: {
      prompt: 'What does emerge contribute to this sentence?',
      context: 'As the fog lifted, a narrow path emerged beside the river.',
      choices: [
        { id: 'a', label: 'The path was built at that exact moment.' },
        { id: 'b', label: 'The path became visible as its cover disappeared.' },
        { id: 'c', label: 'The path became less important.' },
      ],
      correctChoiceId: 'b',
      feedback: 'The path already existed, but it crossed from hidden to visible.',
    },
    contentVersion: 1,
  },
  {
    id: 'unit-restraint',
    articleId: 'article-ink-breathes',
    blockId: 'ink-3',
    expressionConceptId: 'concept-restraint',
    selectedText: 'restraint',
    sentenceText: 'The power of the image often comes from restraint.',
    contextClues: ['The next sentence says the painter does not describe every leaf.', 'Is the painter unable to add detail, or choosing not to?'],
    grammarAndCollocations: ['noun · comes from restraint', 'show / exercise / with restraint'],
    simpleEnglishMeaning: 'the choice not to use all the force or detail available',
    contextualMeaningEn: 'The painting becomes powerful because the artist deliberately holds back detail.',
    contextualSupportZh: '画面的力量来自画家主动克制细节，而不是能力不足。',
    coreConnection: 'The artist has more detail available but intentionally holds it back.',
    relatedContexts: [
      { sentence: 'The actor played the final scene with restraint.', meaningEn: 'The actor kept the emotion controlled instead of making it excessive.', supportZh: '演员克制地处理了最后一幕。', connection: 'Emotional force is available, then deliberately held back.' },
      { sentence: 'Budget restraint slowed the project.', meaningEn: 'Limits were placed on spending.', supportZh: '预算限制拖慢了项目。', connection: 'What is held back here is spending, though the result is less positive.' },
    ],
    transfer: {
      prompt: 'Which sentence shows restraint rather than inability?',
      context: 'Choose the closest example.',
      choices: [
        { id: 'a', label: 'She left the background simple so the figure could breathe.' },
        { id: 'b', label: 'She left the background blank because the file was lost.' },
        { id: 'c', label: 'She added every ornament she could find.' },
      ],
      correctChoiceId: 'a',
      feedback: 'The simplicity is a deliberate holding back that protects the figure.',
    },
    contentVersion: 1,
  },
  {
    id: 'unit-reflect',
    articleId: 'article-ink-breathes',
    blockId: 'ink-4',
    expressionConceptId: 'concept-reflect',
    selectedText: 'reflect',
    sentenceText: 'White space can reflect silence, distance, mist, or light.',
    contextClues: ['White space has no literal voice. What can it make present to the viewer?', 'The following sentences show that nearby marks change how the space feels.'],
    grammarAndCollocations: ['transitive verb · reflect + quality', 'compare: reflect light · reflect a feeling · reflect on a choice'],
    simpleEnglishMeaning: 'to make a quality or feeling visible',
    contextualMeaningEn: 'The empty area can make silence, distance, mist, or light perceptible in the image.',
    contextualSupportZh: '留白能把寂静、距离、雾气或光感呈现出来。',
    coreConnection: 'An invisible quality is returned to the viewer in a visible form.',
    relatedContexts: [
      { sentence: 'The lake reflected the moonlight.', meaningEn: 'Light returned from the lake’s surface.', supportZh: '湖面映出月光。', connection: 'The thing returned here is physical light.' },
      { sentence: 'She reflected on her decision.', meaningEn: 'She brought the decision back into careful thought.', supportZh: '她把那个决定重新带回意识中思考。', connection: 'The thing brought back is a past choice, and on marks the thinking pattern.' },
    ],
    transfer: {
      prompt: 'What is being “returned into view” here?',
      context: 'Her quiet colour choices reflect the mood of early winter.',
      choices: [
        { id: 'a', label: 'Physical light only' },
        { id: 'b', label: 'A seasonal mood made perceptible through colour' },
        { id: 'c', label: 'A decision being reconsidered' },
      ],
      correctChoiceId: 'b',
      feedback: 'The colours make an inner quality—the mood of early winter—perceptible.',
    },
    contentVersion: 1,
  },
  {
    id: 'unit-trace',
    articleId: 'article-ink-breathes',
    blockId: 'ink-5',
    expressionConceptId: 'concept-trace',
    selectedText: 'trace',
    sentenceText: 'Each trace allows us to sense an action that has already ended, so the still image holds a memory of movement.',
    contextClues: ['The previous sentences mention a pale edge and a rough stroke.', 'The original movement has ended. What remains?'],
    grammarAndCollocations: ['countable noun · each trace', 'a trace of + something no longer fully present'],
    simpleEnglishMeaning: 'a small sign left behind by something',
    contextualMeaningEn: 'Each remaining mark gives evidence of the hand or water that once moved there.',
    contextualSupportZh: '每一道残留的痕迹，都让人感到水或手曾经如何运动。',
    coreConnection: 'The action is gone, but a partial sign lets the viewer follow it backward.',
    relatedContexts: [
      { sentence: 'The old wall still carries traces of blue paint.', meaningEn: 'Small pieces of the former paint remain.', supportZh: '旧墙上还留着少量蓝漆痕迹。', connection: 'The former surface is gone, but partial evidence remains.' },
      { sentence: 'Researchers traced the idea through several notebooks.', meaningEn: 'They followed its remaining signs back through time.', supportZh: '研究者沿着笔记中的线索追溯这个想法。', connection: 'As a verb, trace means following the path made by signs.' },
    ],
    transfer: {
      prompt: 'Why is “trace” a better choice than “picture” here?',
      context: 'Only a faint trace of the animal remained in the snow.',
      choices: [
        { id: 'a', label: 'It suggests partial evidence left after the animal moved on.' },
        { id: 'b', label: 'It means a complete portrait of the animal.' },
        { id: 'c', label: 'It means the snow became warmer.' },
      ],
      correctChoiceId: 'a',
      feedback: 'A trace is incomplete but still lets us follow something no longer present.',
    },
    contentVersion: 1,
  },
  {
    id: 'unit-perspective',
    articleId: 'article-ink-breathes',
    blockId: 'ink-6',
    expressionConceptId: 'concept-perspective',
    selectedText: 'perspective',
    sentenceText: 'This way of seeing changes perspective.',
    contextClues: ['The paragraph shifts from the painting as an object to a space completed by the viewer.', 'What changes: the physical paper, or the frame through which we understand it?'],
    grammarAndCollocations: ['countable/uncountable noun', 'change / offer / from a different perspective'],
    simpleEnglishMeaning: 'the position or way of thinking from which something is understood',
    contextualMeaningEn: 'The reader is invited to understand the painting through a different frame.',
    contextualSupportZh: '这种观看方式改变了我们理解画作的视角。',
    coreConnection: 'A new mental position makes different aspects of the painting visible.',
    relatedContexts: [
      { sentence: 'The roof is drawn from a low perspective.', meaningEn: 'The viewer seems to be looking from a low visual position.', supportZh: '屋顶是从较低的视觉位置画出的。', connection: 'The shaping position is physical and visual.' },
      { sentence: 'Travel gave her a different perspective on home.', meaningEn: 'Travel changed the frame through which she understood home.', supportZh: '旅行改变了她理解家乡的方式。', connection: 'The shaping position is mental rather than spatial.' },
    ],
    transfer: {
      prompt: 'Which change is mainly a change of perspective?',
      context: 'Choose the best example.',
      choices: [
        { id: 'a', label: 'The same event is retold through the younger sister’s experience.' },
        { id: 'b', label: 'The canvas is cut into two smaller pieces.' },
        { id: 'c', label: 'The paint takes longer to dry.' },
      ],
      correctChoiceId: 'a',
      feedback: 'The event stays the same, but the position shaping what we notice changes.',
    },
    contentVersion: 1,
  },
  ...expandedLearningUnits,
]
